# Generated by Django 5.0.4 on 2024-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField()),
                ('title', models.TextField()),
                ('isPlayed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('imageUrl', models.TextField()),
                ('youtubeUrl', models.TextField()),
            ],
        ),
    ]
