# Generated by Django 5.0.4 on 2024-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
        migrations.AlterField(
            model_name='record',
            name='isPlayed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
